# Generated by Django 4.2.5 on 2024-10-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_wallet_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.wallet'),
        ),
    ]
