# Generated by Django 4.2.5 on 2024-10-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_id',
        ),
    ]
