# Generated by Django 4.2.5 on 2024-10-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_id',
        ),
    ]
