# Generated by Django 4.2.5 on 2024-10-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.room'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
