# Generated by Django 4.2.5 on 2024-10-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_user_wallet_user_chat_id_delete_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
