# Generated by Django 4.2.5 on 2024-10-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
